# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/cheeseburger/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),cheeseburger)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,1fe9183e6a36cdf3324037501f8c552f2f315c68)
$(call add-radio-file-sha1-checked,radio/modem.img,55e34e0a30e815aa640e4b4f6b2288d45390d7d2)
$(call add-radio-file-sha1-checked,radio/abl.img,b0f73a28ca9a176ece7c12271e66df758b9fb972)
$(call add-radio-file-sha1-checked,radio/dsp.img,9efd0c326cd631cdbeed4678cfafafd5265a9e73)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,96f9d1b07e35d460de170207d3b3da632fa176db)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,2df0a7eab656ba4c4026cf5f9836aa43cb0ec13c)
$(call add-radio-file-sha1-checked,radio/devcfg.img,8c7b9fed3662d92b0ac3c3ae313ca4d1c390f84f)
$(call add-radio-file-sha1-checked,radio/hyp.img,66647a5edb93cc9ceb8a3a2b9fbe084a5ca04706)
$(call add-radio-file-sha1-checked,radio/keymaster.img,81c0119b130a9bc573501764bc4ceea500d947dc)
$(call add-radio-file-sha1-checked,radio/LOGO.img,2b932fbe792a423a6d0dff2fbe3e1083753b49b6)
$(call add-radio-file-sha1-checked,radio/pmic.img,919c49b79a41b514bb92dc6832d0c960f84817a9)
$(call add-radio-file-sha1-checked,radio/rpm.img,c9ac0e6b3fdd27465be42268c07343837e24d9cf)
$(call add-radio-file-sha1-checked,radio/tz.img,2eb74ecdf16db7dea3787ccb926966017e4188a5)
$(call add-radio-file-sha1-checked,radio/xbl.img,e2b571bb0054d3017423daf4506d45826f651f26)

endif
